# Example OXDK project -- minimal D3D app
#
# Usage:
#   1. Make sure your XDK libs/headers are in ../../xdk/
#   2. Run: make
#   3. Copy bin/default.xbe to your Xbox

OXDK_DIR  = ../..
XBE_TITLE = Hello
XBE_MODE  = RETAIL

SRCS = main.cpp

include $(OXDK_DIR)/oxdk.mk
