#!/usr/bin/env python3
"""Build a XEX that declares a chosen set of imports, to find which ones the console has.

An import the loader cannot resolve makes it reject the whole module, silently. That makes
a failing title hard to diagnose, because the failure looks identical whatever the cause.
This builds a minimal XEX that declares the imports under test but calls only DbgPrint, so
loading at all is the signal: if it prints, every declared import resolved on this console.

Bisecting a large import list then costs a handful of boots rather than one per import.

    probe.py --imports imports.txt -o default.xex
    imports.txt: one "library ordinal type" per line, e.g. "xboxkrnl.exe 132 0"
"""
import argparse, os, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..', 'common'))
import toolchain

CLANG = toolchain.tool('clang')
OBJCOPY = toolchain.tool('llvm-objcopy')
NM = toolchain.tool('llvm-nm', 'LLVM_NM')
LLD = os.environ.get('LLD', 'ld.lld')
TARGET = 'powerpc-unknown-none-elf'

LIBORDER = ['xam.xex', 'xboxkrnl.exe']
LIBINFO = {'xam.xex': ('2.0.21256.0', '2.0.1861.0', '0xfca15c76'),
           'xboxkrnl.exe': ('2.0.21256.0', '2.0.1861.0', '0x45dc17e0')}

ASM = '''// generated by probe.py
    .section .pehdr, "a"
    .space 0x400

    .section .rdata, "a"
    .globl  slot_DbgPrint
slot_DbgPrint:              .space 4
    .globl  slot_HalReturnToFirmware
slot_HalReturnToFirmware:   .space 4
%(slots)s
msg:
    .asciz  "OXDK360 probe: all declared imports resolved\\n"

    .section .text, "ax"
    .globl  _start
_start:
    mflr    12
    stwu    1, -144(1)
    lis     3, msg@ha
    addi    3, 3, msg@l
    bl      thunk_DbgPrint
    li      3, 1
    bl      thunk_HalReturnToFirmware
hang:
    b       hang

    .align  4
    .globl  thunk_DbgPrint
thunk_DbgPrint:             .space 16
    .globl  thunk_HalReturnToFirmware
thunk_HalReturnToFirmware:  .space 16
%(thunks)s

    .section .pdata, "a"
    .long   _start
    .long   0x40000602
%(extra)s
'''

LD = '''ENTRY(_start)
SECTIONS {
    . = 0x82000000;
    .pehdr : { *(.pehdr) }
    . = 0x82000400;
    .rdata : { *(.rdata) }
    . = 0x8200F000;
    .pdata : { *(.pdata) }
    . = 0x82010000;
    .text  : { *(.text) }
    . = 0x82020000;
    .xdata : { *(.xdata) }
    . = 0x82030000;
    .data  : { *(.dsec) }
    /DISCARD/ : { *(.comment) *(.note*) *(.eh_frame*) }
}
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--imports', required=True)
    ap.add_argument('-o', '--output', required=True)
    ap.add_argument('--work', default=None)
    ap.add_argument('--xdata', action='store_true',
                    help='add an .xdata section, as a title linked against the XDK has')
    ap.add_argument('--data', action='store_true',
                    help='add a writable .data page')
    ap.add_argument('--pad', default='0',
                    help='pad the image to at least this size')
    a = ap.parse_args()

    entries = []
    for line in open(a.imports):
        line = line.split('#')[0].strip()
        if not line:
            continue
        lib, ordinal, typ = line.split()
        entries.append((lib, int(ordinal), int(typ)))

    work = a.work or os.path.join(os.path.dirname(os.path.abspath(a.output)), '.probe')
    os.makedirs(work, exist_ok=True)

    slots, thunks = [], []
    for lib, ordinal, typ in entries:
        tag = f"{lib.split('.')[0]}_{ordinal}"
        slots.append(f"    .globl  slot_{tag}\nslot_{tag}:  .space 4")
        if typ == 0:
            thunks.append(f"    .globl  thunk_{tag}\nthunk_{tag}: .space 16")

    src = os.path.join(work, 'probe.S')
    extra = ''
    if a.xdata:
        extra += '\n    .section .xdata, "a"\n    .long 0x00000001\n    .space 0x1b0\n'
    if a.data:
        extra += '\n    .section .dsec, "aw"\n    .long 0x12345678\n    .space 0xc4c\n'
    open(src, 'w').write(ASM % {'slots': '\n'.join(slots), 'thunks': '\n'.join(thunks),
                                'extra': extra})
    open(os.path.join(work, 'probe.ld'), 'w').write(LD)

    obj = os.path.join(work, 'probe.o')
    elf = os.path.join(work, 'probe.elf')
    binimg = os.path.join(work, 'probe.bin')
    subprocess.run([CLANG, '-target', TARGET, '-c', src, '-o', obj], check=True)
    subprocess.run([LLD, '-T', os.path.join(work, 'probe.ld'), '-o', elf, obj], check=True)
    subprocess.run([OBJCOPY, '-O', 'binary', elf, binimg], check=True)

    out = subprocess.run([NM, elf], capture_output=True, text=True).stdout
    syms = {p[2]: int(p[0], 16) for p in (l.split() for l in out.splitlines()) if len(p) == 3}
    size = os.path.getsize(binimg)

    mf = os.path.join(work, 'probe.mf')
    with open(mf, 'w') as f:
        f.write("# generated by probe.py\nbase 0x82000000\n")
        f.write(f"entry 0x{syms['_start']:08x}\nstack 0x10000\ntitleid 0x0\n")
        f.write("sysflags 0x00000001\npename probe.exe\n\n")
        f.write("section .rdata 400 e000 40000040\n")
        f.write("section .pdata f000 8 40000040\n")
        f.write(f"section .text 10000 fc00 60000020\n")
        if a.xdata:
            f.write("section .xdata 20000 fc00 40000040\n")
        if a.data:
            f.write(f"section .data 30000 {max(size - 0x30000, 0x100):x} c0000040\n")
        for lib in LIBORDER:
            rows = [(o, t) for l, o, t in entries if l == lib]
            base = [('DbgPrint', 3, 0), ('HalReturnToFirmware', 40, 0)] if lib == 'xboxkrnl.exe' else []
            if not rows and not base:
                continue
            ver, vmin, libid = LIBINFO[lib]
            f.write(f"\nlibrary {lib} {ver} {vmin} {libid}\n")
            for name, ordinal, typ in base:
                f.write(f"import {ordinal} {syms['slot_' + name]:x} {syms['thunk_' + name]:x}\n")
            for ordinal, typ in rows:
                tag = f"{lib.split('.')[0]}_{ordinal}"
                if typ == 0:
                    f.write(f"import {ordinal} {syms['slot_' + tag]:x} {syms['thunk_' + tag]:x}\n")
                else:
                    f.write(f"import {ordinal} {syms['slot_' + tag]:x}\n")

    cxex = os.path.join(HERE, '..', 'cxex', 'cxex')
    subprocess.run([cxex, '-m', mf, '-i', binimg, '-o', a.output], check=True)
    print(f"  probe declares {len(entries)} imports under test")


if __name__ == '__main__':
    main()
