# Clear the screen using the real XDK D3D.
OXDK_DIR    := ../../..
OXDK_TARGET := xbox360
SRCS        := main.c shim.S
XEX_TITLE   := d3dclear
XDK_LIBS    := xapilib,d3d9,libcMT
include $(OXDK_DIR)/oxdk.mk
